### ISSUE TITLE
collectLocalReport util method requires "packages" base folder

### ISSUE THREAD

**Issue by benkeen** [microsoft/monosize#61]
Hey @layershifter, would you be amenable to a PR to make "packages" folder here a configurable setting on `CollectLocalReportOptions`?
https://github.com/microsoft/monosize/blob/2db473d8effc2fe2288d9c5f33b0db721e9cd359/packages/monosize/src/utils/collectLocalReport.mts#L46

Our monorepo uses Rush and has a differently-named base folder for our packages.

**Comment by layershifter** [comment]
That's already supported, but not documented. See https://github.com/microsoft/monosize/pull/26

**Comment by benkeen** [comment]
Excellent, thanks @layershifter!
