### ISSUE TITLE
Feature request: customizable generation folder

### ISSUE THREAD

**Issue by benkeen** [microsoft/monosize#63]
Correct me if I'm wrong, but I don't see an option to generate the monosize results in any other location than `dist/bundle-size/*`. 

We use Rush for our monorepo which for its caching layer needs a clear 1-1 mapping of commands to output locations. Since /dist is already being generated by the "build" cmd, we need a different location for the output of monosize.

We can workaround it with a quick script to copy from A to B, but being able to specify a custom target folder would simplify our integration. Thanks!

**Comment by layershifter** [comment]
@benkeen yes, this indeed is not supported. Would be nice to have.

**Comment by sarmad-abualkaz** [comment]
@layershifter let me know what you think of this PR please? 
https://github.com/microsoft/monosize/pull/66

**Comment by layershifter** [comment]
FYI fixed in #66, I triggered a release, so it will be on NPM in ~10 minutes.
