### ISSUE TITLE
An option to create file and write the `compare-report` output for markdownReporter 

### ISSUE THREAD

**Issue by sarmad-abualkaz** [microsoft/monosize#64]
Curious if there are any interests in making `monosize compare-report` take on an option to also create and write output to a local file?

We have a requirement to make our pipeline (and monorepo) OS-agnostic, and were hoping to have monosize create the report file and write the report output in a codified-manner, rather than using some linux utility (e.g. `tee` or just writing stdout via `>`).

I already [put together a branch](https://github.com/microsoft/monosize/compare/main...sarmad-abualkaz:monosize:ft/compare-reports-create-and-write-to-file) that does this (with optional `--outputFile` argument) and would love to create a PR if that's something you are interested in entertaining/addressing? Let me know.

**Comment by layershifter** [comment]
We made this change intentionally to behave like other tools in ecosystem (#39). This also makes other reporters consistent as there is a plan to expose API for custom reporters.
